# Generated by Django 4.2.6 on 2023-10-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_neme', models.CharField(default='', max_length=50)),
                ('FirstName', models.CharField(max_length=50)),
                ('MiddleName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=19)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(default='2', max_length=6)),
                ('Aadhar', models.FileField(blank=True, default='', null=True, upload_to='images/')),
                ('Pancard', models.FileField(blank=True, default='', null=True, upload_to='images/')),
                ('Incomecerti', models.FileField(blank=True, default='', null=True, upload_to='images/')),
                ('Castcerti', models.FileField(blank=True, default='', null=True, upload_to='images/')),
                ('photo', models.FileField(blank=True, default='', null=True, upload_to='images/')),
                ('Birthcerti', models.FileField(blank=True, default='', null=True, upload_to='images/')),
                ('sign', models.FileField(blank=True, default='', null=True, upload_to='images/')),
                ('educationalCerti', models.FileField(blank=True, default='', null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_name', models.CharField(default='', max_length=50)),
                ('FirstName', models.CharField(max_length=50)),
                ('MiddleName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=19)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(default='2', max_length=6)),
                ('ac_name', models.CharField(max_length=50)),
                ('ac_no', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=50)),
                ('Aadhar', models.FileField(blank=True, default='', null=True, upload_to='images/')),
                ('Pancard', models.FileField(blank=True, default='', null=True, upload_to='images/')),
                ('Incomecerti', models.FileField(blank=True, default='', null=True, upload_to='images/')),
                ('Castcerti', models.FileField(blank=True, default='', null=True, upload_to='images/')),
                ('photo', models.FileField(blank=True, default='', null=True, upload_to='images/')),
                ('Birthcerti', models.FileField(blank=True, default='', null=True, upload_to='images/')),
                ('sign', models.FileField(blank=True, default='', null=True, upload_to='images/')),
                ('educationalCerti', models.FileField(blank=True, default='', null=True, upload_to='images/')),
            ],
        ),
    ]
