# Generated by Django 4.2.6 on 2023-11-28 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_login_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='password',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.register'),
        ),
    ]
